-- BATIMAG Seed Data
-- Sample data for development and testing

-- ===========================================
-- ARTICLES SEED DATA
-- ===========================================
INSERT INTO public.articles (slug, title, excerpt, content, category, author_name, reading_time, is_featured, cover_image) VALUES
('nouveau-pont-conakry-kamsar', 
 'Le nouveau pont Conakry-Kamsar: Un projet structurant pour la Guinee', 
 'Decouvrez les details du projet de construction du pont reliant Conakry a Kamsar, un ouvrage majeur pour le desenclavement de la region.',
 '<p>Le gouvernement guineen a annonce le lancement du projet de construction d''un pont strategique reliant Conakry a Kamsar. Ce projet d''envergure, estime a plusieurs centaines de millions de dollars, vise a revolutionner les echanges commerciaux entre la capitale et la region de Boke.</p><h2>Un ouvrage d''art majeur</h2><p>Long de 4,5 kilometres, ce pont a haubans sera le plus grand ouvrage d''art jamais construit en Guinee. Il comprendra quatre voies de circulation, une piste cyclable et un trottoir pour pietons.</p><h2>Impact economique</h2><p>Les experts estiment que ce pont permettra de reduire de 60% le temps de trajet entre Conakry et Kamsar, facilitant ainsi l''acheminement des marchandises vers le port de Kamsar.</p>',
 'infrastructures', 
 'Mamadou Diallo', 
 8, 
 true,
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=1200'),

('materiaux-construction-ecologiques-guinee',
 'Les materiaux de construction ecologiques gagnent du terrain en Guinee',
 'Une nouvelle tendance emerge dans le secteur du BTP guineen: l''utilisation de materiaux locaux et durables.',
 '<p>Face aux enjeux environnementaux et economiques, de plus en plus d''entreprises guineennes se tournent vers les materiaux de construction ecologiques. Cette tendance marque un tournant dans l''industrie du batiment en Guinee.</p><h2>La brique en terre compressee</h2><p>La BTC (Brique en Terre Compressee) connait un essor remarquable. Fabriquee a partir de terre locale, elle offre une excellente isolation thermique et un cout reduit de 40% par rapport aux materiaux importes.</p>',
 'materiaux',
 'Aissatou Barry',
 6,
 false,
 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200'),

('nouveau-code-urbanisme-2024',
 'Nouveau code de l''urbanisme: Ce qui change pour les professionnels',
 'Le gouvernement a adopte un nouveau code de l''urbanisme. Analyse des principales modifications et leurs impacts.',
 '<p>Le nouveau code de l''urbanisme, adopte en decembre 2024, introduit des changements majeurs pour les professionnels du BTP et de l''immobilier en Guinee.</p><h2>Simplification des procedures</h2><p>Les delais d''obtention des permis de construire sont reduits de 90 a 45 jours. Une plateforme numerique permettra de soumettre les demandes en ligne.</p><h2>Normes parasismiques</h2><p>De nouvelles normes parasismiques sont desormais obligatoires pour toute construction de plus de trois etages.</p>',
 'reglementation',
 'Ibrahima Sow',
 7,
 true,
 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200'),

('energie-solaire-chantiers-btp',
 'Energie solaire: La revolution silencieuse des chantiers BTP',
 'De plus en plus de chantiers guineens adoptent l''energie solaire pour alimenter leurs operations.',
 '<p>L''energie solaire transforme progressivement le secteur de la construction en Guinee. Des generateurs diesel aux panneaux photovoltaiques, les chantiers font leur transition energetique.</p>',
 'energie',
 'Oumar Camara',
 5,
 false,
 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200'),

('techniques-genie-civil-modernes',
 'Les techniques modernes de genie civil arrivent en Guinee',
 'Decouvrez comment les nouvelles technologies revolutionnent le genie civil guineen.',
 '<p>Le genie civil guineen entre dans une nouvelle ere avec l''adoption de technologies de pointe. Du BIM aux drones, les outils modernes transforment la facon de construire.</p>',
 'genie-civil',
 'Fatoumata Keita',
 6,
 false,
 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200'),

('immeubles-bureaux-kaloum',
 'Boom immobilier a Kaloum: 5 nouveaux immeubles de bureaux en construction',
 'Le quartier d''affaires de Conakry connait une dynamique sans precedent avec plusieurs projets immobiliers majeurs.',
 '<p>Kaloum, le centre nevralgique des affaires a Conakry, voit emerger cinq nouveaux immeubles de bureaux modernes. Ces projets totalisent plus de 50,000 metres carres de surface de bureaux.</p>',
 'batiment',
 'Alpha Conde',
 5,
 true,
 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200');

-- ===========================================
-- COMPANIES SEED DATA
-- ===========================================
INSERT INTO public.companies (slug, name, description, long_description, category, subcategory, address, city, country, phone, email, website, year_founded, employees_count, is_verified, is_premium, rating, reviews_count, certifications, services, projects_completed) VALUES
('sogea-satom-guinee',
 'SOGEA-SATOM Guinee',
 'Leader des travaux publics et du genie civil en Afrique de l''Ouest, present en Guinee depuis 1960.',
 '<p>SOGEA-SATOM est une filiale du groupe VINCI Construction, leader mondial de la construction. Presente en Guinee depuis plus de 60 ans, l''entreprise a participe aux plus grands projets d''infrastructure du pays.</p><p>Notre expertise couvre les routes, ponts, barrages, ports et batiments industriels. Nous employons plus de 500 personnes en Guinee et formons chaque annee des dizaines de jeunes aux metiers du BTP.</p>',
 'Genie Civil',
 'Travaux Publics',
 'Quartier Almamya, Commune de Kaloum',
 'Conakry',
 'Guinee',
 '+224 622 00 00 00',
 'contact@sogea-guinee.com',
 'https://www.sogea-satom.com',
 1960,
 '500+',
 true,
 true,
 4.8,
 45,
 ARRAY['ISO 9001', 'ISO 14001', 'OHSAS 18001'],
 ARRAY['Construction de routes', 'Ouvrages d''art', 'VRD', 'Batiments industriels', 'Hydraulique'],
 150),

('colas-guinee',
 'COLAS Guinee',
 'Specialiste de la construction et l''entretien des infrastructures de transport.',
 '<p>COLAS Guinee fait partie du groupe COLAS, leader mondial de la construction de routes. Notre mission est de developper des infrastructures de transport durables et de qualite en Guinee.</p>',
 'Genie Civil',
 'Routes et Autoroutes',
 'Zone Industrielle de Matoto',
 'Conakry',
 'Guinee',
 '+224 628 00 00 00',
 'info@colas-guinee.com',
 'https://www.colas.com',
 1975,
 '200-500',
 true,
 true,
 4.6,
 32,
 ARRAY['ISO 9001', 'ISO 14001'],
 ARRAY['Construction routiere', 'Enrobes', 'Terrassement', 'Assainissement'],
 85),

('btp-guinee-construction',
 'BTP Guinee Construction',
 'Entreprise guineenne specialisee dans la construction de batiments residentiels et commerciaux.',
 '<p>BTP Guinee Construction est une entreprise 100% guineenne fondee en 2005. Nous sommes specialises dans la construction de batiments residentiels, commerciaux et industriels de haute qualite.</p>',
 'Batiment',
 'Construction Generale',
 'Quartier Ratoma Centre',
 'Conakry',
 'Guinee',
 '+224 620 00 00 00',
 'contact@btpguinee.com',
 'https://www.btpguinee.com',
 2005,
 '50-200',
 true,
 false,
 4.3,
 18,
 ARRAY['Agree Etat Guineen'],
 ARRAY['Gros oeuvre', 'Second oeuvre', 'Renovation', 'Amenagement interieur'],
 45),

('lafarge-holcim-guinee',
 'Lafarge Holcim Guinee',
 'Premier producteur de ciment en Guinee, fournisseur de solutions pour la construction durable.',
 '<p>Lafarge Holcim Guinee est le leader de la production de ciment en Guinee. Notre usine de Conakry produit annuellement plus de 500,000 tonnes de ciment de haute qualite.</p>',
 'Materiaux',
 'Ciment et Beton',
 'Zone Industrielle de Sonfonia',
 'Conakry',
 'Guinee',
 '+224 624 00 00 00',
 'info@lafargeholcim-gn.com',
 'https://www.lafargeholcim.com',
 1998,
 '200-500',
 true,
 true,
 4.7,
 28,
 ARRAY['ISO 9001', 'ISO 14001', 'CE'],
 ARRAY['Ciment Portland', 'Beton pret a l''emploi', 'Granulats', 'Services techniques'],
 0),

('elecnor-guinee',
 'Elecnor Guinee',
 'Expert en installations electriques et energies renouvelables.',
 '<p>Elecnor Guinee est specialisee dans les installations electriques industrielles et les projets d''energie renouvelable. Nous accompagnons la transition energetique de la Guinee.</p>',
 'Energie',
 'Electricite Industrielle',
 'Quartier Dixinn Port',
 'Conakry',
 'Guinee',
 '+224 625 00 00 00',
 'guinee@elecnor.com',
 'https://www.elecnor.com',
 2010,
 '50-200',
 true,
 false,
 4.4,
 15,
 ARRAY['ISO 9001', 'QUALIFELEC'],
 ARRAY['Installation electrique', 'Energie solaire', 'Maintenance', 'Audit energetique'],
 35);

-- ===========================================
-- JOBS SEED DATA
-- ===========================================
INSERT INTO public.jobs (slug, title, company_name, description, requirements, location, country, contract_type, sector, salary_range, is_urgent, is_featured, experience_level, application_email) VALUES
('ingenieur-genie-civil-sogea',
 'Ingenieur Genie Civil Senior',
 'SOGEA-SATOM Guinee',
 '<p>Nous recherchons un Ingenieur Genie Civil Senior pour superviser nos projets d''infrastructure en Guinee. Vous serez responsable de la gestion technique des chantiers et de l''encadrement des equipes.</p><h3>Missions</h3><ul><li>Supervision technique des chantiers</li><li>Management des equipes terrain</li><li>Coordination avec les bureaux d''etudes</li><li>Respect des delais et budgets</li></ul>',
 '<ul><li>Diplome d''ingenieur en Genie Civil (Bac+5)</li><li>Minimum 7 ans d''experience en travaux publics</li><li>Experience en Afrique appreciee</li><li>Maitrise d''AutoCAD et MS Project</li><li>Francais courant, anglais professionnel</li></ul>',
 'Conakry',
 'Guinee',
 'CDI',
 'Genie Civil',
 '15 000 000 - 25 000 000 GNF',
 true,
 true,
 'Senior (7+ ans)',
 'recrutement@sogea-guinee.com'),

('chef-chantier-colas',
 'Chef de Chantier Routes',
 'COLAS Guinee',
 '<p>COLAS Guinee recrute un Chef de Chantier pour ses projets routiers dans la region de Boke.</p>',
 '<ul><li>BTS/DUT Travaux Publics</li><li>5 ans d''experience minimum</li><li>Permis B obligatoire</li></ul>',
 'Boke',
 'Guinee',
 'CDI',
 'Travaux Publics',
 '8 000 000 - 12 000 000 GNF',
 false,
 false,
 'Confirme (5-7 ans)',
 'rh@colas-guinee.com'),

('architecte-junior',
 'Architecte Junior',
 'BTP Guinee Construction',
 '<p>Rejoignez notre equipe d''architectes pour participer a des projets immobiliers innovants a Conakry.</p>',
 '<ul><li>Diplome d''architecte (DPLG ou equivalent)</li><li>1-3 ans d''experience</li><li>Maitrise d''ArchiCAD et Revit</li></ul>',
 'Conakry',
 'Guinee',
 'CDI',
 'Architecture',
 '5 000 000 - 8 000 000 GNF',
 false,
 true,
 'Junior (1-3 ans)',
 'jobs@btpguinee.com'),

('technicien-electricien',
 'Technicien Electricien Industriel',
 'Elecnor Guinee',
 '<p>Nous recherchons un technicien electricien pour nos installations industrielles et projets solaires.</p>',
 '<ul><li>CAP/BEP Electricite</li><li>3 ans d''experience minimum</li><li>Habilitations electriques</li></ul>',
 'Conakry',
 'Guinee',
 'CDD',
 'Electricite',
 '4 000 000 - 6 000 000 GNF',
 true,
 false,
 'Confirme (3-5 ans)',
 'emploi@elecnor-guinee.com'),

('stagiaire-btp',
 'Stage Ingenieur BTP',
 'SOGEA-SATOM Guinee',
 '<p>Stage de fin d''etudes de 6 mois pour futur ingenieur BTP. Encadrement par des professionnels experimentes.</p>',
 '<ul><li>Etudiant Bac+4/5 en Genie Civil</li><li>Stage de fin d''etudes</li><li>Motivation et rigueur</li></ul>',
 'Conakry',
 'Guinee',
 'Stage',
 'Genie Civil',
 '1 500 000 GNF/mois',
 false,
 false,
 'Stage',
 'stages@sogea-guinee.com');

-- ===========================================
-- TRAININGS SEED DATA
-- ===========================================
INSERT INTO public.trainings (slug, title, institution, description, objectives, program, prerequisites, domain, level, mode, duration, price, max_participants, location, certification, is_featured) VALUES
('bim-management-fondamentaux',
 'BIM Management: Les Fondamentaux',
 'Institut Guineen du BTP',
 '<p>Formation complete au Building Information Modeling (BIM). Apprenez a maitriser les outils et methodes de la maquette numerique pour optimiser vos projets de construction.</p>',
 ARRAY['Comprendre les principes du BIM', 'Maitriser Revit Architecture', 'Gerer la collaboration BIM', 'Produire des maquettes conformes'],
 '<h3>Module 1: Introduction au BIM (8h)</h3><p>Historique, concepts, niveaux de maturite BIM</p><h3>Module 2: Revit Fondamentaux (16h)</h3><p>Interface, modelisation, familles, nomenclatures</p><h3>Module 3: Collaboration BIM (8h)</h3><p>Travail collaboratif, formats IFC, plateformes</p>',
 ARRAY['Connaissance de base en CAO', 'Notions de construction', 'Ordinateur avec Revit installe'],
 'BIM & Numerique',
 'Intermediaire',
 'Presentiel',
 '5 jours (32h)',
 2500000,
 15,
 'Conakry',
 'Certificat BIM Fondamentaux - IGBTP',
 true),

('securite-chantier',
 'Securite et Prevention des Risques sur Chantier',
 'Centre de Formation BTP Afrique',
 '<p>Formation obligatoire pour tous les intervenants sur chantier. Apprenez les regles de securite et la prevention des accidents du travail.</p>',
 ARRAY['Identifier les risques sur chantier', 'Appliquer les regles de securite', 'Utiliser les EPI correctement', 'Reagir en cas d''accident'],
 '<h3>Jour 1: Les risques du BTP</h3><p>Statistiques, types de risques, reglementation</p><h3>Jour 2: Prevention pratique</h3><p>EPI, signalisation, gestes et postures</p><h3>Jour 3: Premiers secours</h3><p>Gestes d''urgence, evacuation</p>',
 ARRAY['Aucun prerequis', 'Aptitude physique'],
 'Securite',
 'Debutant',
 'Presentiel',
 '3 jours (24h)',
 800000,
 20,
 'Conakry',
 'Attestation Securite Chantier',
 false),

('gestion-projet-construction',
 'Gestion de Projet de Construction',
 'Universite Gamal Abdel Nasser',
 '<p>Formation executive en gestion de projet appliquee au secteur de la construction. Methodes, outils et bonnes pratiques pour mener vos projets a bien.</p>',
 ARRAY['Planifier un projet de construction', 'Gerer budgets et ressources', 'Piloter les parties prenantes', 'Maitriser MS Project'],
 '<h3>Semaine 1: Fondamentaux</h3><p>Cycle de vie projet, WBS, diagramme de Gantt</p><h3>Semaine 2: Outils</h3><p>MS Project, Excel avance, tableaux de bord</p><h3>Semaine 3: Cas pratiques</h3><p>Etudes de cas reels, simulation</p>',
 ARRAY['Bac+2 minimum', '2 ans d''experience en BTP', 'Notions d''Excel'],
 'Management',
 'Avance',
 'Hybride',
 '3 semaines',
 4500000,
 12,
 'Conakry',
 'Certificat Gestion de Projet Construction',
 true),

('autocad-construction',
 'AutoCAD pour la Construction',
 'Institut Guineen du BTP',
 '<p>Maitrisez AutoCAD pour produire des plans de construction professionnels. Formation pratique avec exercices sur projets reels.</p>',
 ARRAY['Maitriser l''interface AutoCAD', 'Dessiner des plans 2D', 'Coter et annoter', 'Imprimer et exporter'],
 '<h3>Module 1: Prise en main</h3><p>Interface, outils de base, navigation</p><h3>Module 2: Dessin 2D</h3><p>Lignes, formes, calques, blocs</p><h3>Module 3: Production</h3><p>Cotation, mise en page, impression</p>',
 ARRAY['Aucune experience AutoCAD requise', 'Connaissance Windows'],
 'CAO/DAO',
 'Debutant',
 'Presentiel',
 '4 jours (28h)',
 1800000,
 10,
 'Conakry',
 'Certificat AutoCAD Niveau 1',
 false),

('energie-solaire-batiment',
 'Integration Energie Solaire dans le Batiment',
 'Ecole Superieure Polytechnique',
 '<p>Formation specialisee sur l''integration des systemes solaires photovoltaiques et thermiques dans les batiments neufs et existants.</p>',
 ARRAY['Dimensionner une installation PV', 'Integrer le solaire au bati', 'Calculer la rentabilite', 'Respecter les normes'],
 '<h3>Partie 1: Fondamentaux solaires</h3><p>Gisement, technologies, composants</p><h3>Partie 2: Dimensionnement</h3><p>Calculs, logiciels, cas pratiques</p><h3>Partie 3: Installation</h3><p>Mise en oeuvre, maintenance, securite</p>',
 ARRAY['Bac+2 technique', 'Notions d''electricite'],
 'Energie',
 'Intermediaire',
 'E-learning',
 '40 heures',
 1200000,
 30,
 'En ligne',
 'Certificat Energie Solaire Batiment',
 true);

-- ===========================================
-- EVENTS SEED DATA
-- ===========================================
INSERT INTO public.events (slug, title, description, long_description, event_type, location, address, city, country, is_online, start_date, end_date, registration_url, price, organizer_name, max_attendees, is_featured, cover_image) VALUES
('salon-batimag-2026',
 'Salon BATIMAG 2026 - Le Rendez-vous du BTP Guineen',
 'Le plus grand salon professionnel du BTP en Guinee. 3 jours de rencontres, conferences et innovations.',
 '<p>Le Salon BATIMAG 2026 reunit tous les acteurs du BTP guineen pendant 3 jours intenses. Exposants, conferences, networking: un evenement incontournable pour les professionnels du secteur.</p><h3>Au programme</h3><ul><li>Plus de 100 exposants</li><li>20 conferences thematiques</li><li>Espace recrutement</li><li>Zone innovation et startups</li></ul>',
 'salon',
 'Palais du Peuple',
 'Boulevard du Commerce, Kaloum',
 'Conakry',
 'Guinee',
 false,
 '2026-05-15 09:00:00+00',
 '2026-05-17 18:00:00+00',
 'https://salon.batimag.gn/inscription',
 50000,
 'BATIMAG',
 2000,
 true,
 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200'),

('webinaire-reglementation-2026',
 'Webinaire: Nouveau Code de l''Urbanisme 2026',
 'Decouvrez en direct les changements du nouveau code de l''urbanisme et leur impact sur vos projets.',
 '<p>Webinaire gratuit presente par des experts juridiques du BTP. Comprenez les nouvelles regles et anticipez leur mise en application.</p>',
 'webinaire',
 'En ligne',
 '',
 'Conakry',
 'Guinee',
 true,
 '2026-04-10 14:00:00+00',
 '2026-04-10 16:00:00+00',
 'https://webinaire.batimag.gn/urbanisme',
 0,
 'BATIMAG',
 500,
 true,
 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=1200'),

('conference-bim-afrique',
 'Conference BIM Afrique 2026',
 'La transformation numerique du BTP africain: enjeux et opportunites du BIM.',
 '<p>Rejoignez les leaders du BIM en Afrique pour deux jours de conferences et ateliers pratiques sur la maquette numerique.</p>',
 'conference',
 'Hotel Noom Conakry',
 'Avenue de la Republique, Kaloum',
 'Conakry',
 'Guinee',
 false,
 '2026-06-20 08:30:00+00',
 '2026-06-21 17:00:00+00',
 'https://bim-afrique.com/inscription',
 150000,
 'BuildTech Africa',
 300,
 false,
 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=1200'),

('networking-femmes-btp',
 'Networking: Femmes dans le BTP',
 'Soiree de networking dediee aux femmes professionnelles du secteur de la construction.',
 '<p>Un moment de partage et de networking entre femmes du BTP. Temoignages, echanges et opportunites de collaboration.</p>',
 'networking',
 'Restaurant Le Petit Bateau',
 'Corniche Nord, Dixinn',
 'Conakry',
 'Guinee',
 false,
 '2026-04-25 18:30:00+00',
 '2026-04-25 21:30:00+00',
 NULL,
 25000,
 'Association Femmes BTP Guinee',
 50,
 false,
 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200');
