-- Seed Events
INSERT INTO events (slug, title, description, long_description, cover_image, event_type, location, address, city, country, start_date, end_date, is_featured, is_online, price, currency, max_attendees, organizer_name, registration_url) VALUES
('salon-btp-africa-2026', 'Salon International BTP Africa 2026', 'Le plus grand salon professionnel dédié à la construction et aux infrastructures en Afrique.', 'Le Salon BTP Africa rassemble chaque année plus de 500 exposants et 25 000 visiteurs professionnels venus de tout le continent africain. Cet événement majeur est l''occasion unique de découvrir les dernières innovations en matière de construction, de rencontrer les acteurs clés du secteur et de développer votre réseau professionnel.', '/images/event-1.jpg', 'Salon', 'Parc des Expositions', '123 Boulevard Hassan II', 'Casablanca', 'Maroc', '2026-06-15 09:00:00+00', '2026-06-18 18:00:00+00', true, false, 150, 'MAD', 25000, 'BATIMAG Events', 'https://example.com/register'),
('conference-genie-civil-dakar', 'Conférence Génie Civil Dakar 2026', 'Conférence internationale sur les nouvelles techniques de génie civil en Afrique de l''Ouest.', 'Cette conférence réunit les experts et professionnels du génie civil pour échanger sur les meilleures pratiques et innovations du secteur.', '/images/event-2.jpg', 'Conférence', 'Centre de Conférences', 'Avenue Cheikh Anta Diop', 'Dakar', 'Sénégal', '2026-04-22 08:30:00+00', '2026-04-24 17:00:00+00', false, false, 200, 'EUR', 1000, 'ECOWAS Construction', 'https://example.com/register'),
('webinar-construction-durable', 'Webinar : Construction Durable en Afrique', 'Découvrez les enjeux et solutions pour une construction plus respectueuse de l''environnement.', 'Un webinar interactif avec des experts internationaux sur la construction durable.', null, 'Webinar', 'En ligne', null, 'En ligne', 'International', '2026-03-28 14:00:00+00', '2026-03-28 16:00:00+00', false, true, 0, 'EUR', 500, 'BATIMAG Academy', 'https://example.com/register'),
('forum-infrastructure-abidjan', 'Forum Infrastructure Abidjan 2026', 'Forum dédié aux grands projets d''infrastructure en Côte d''Ivoire et en Afrique de l''Ouest.', 'Le Forum Infrastructure d''Abidjan réunit décideurs, investisseurs et professionnels pour discuter des opportunités du secteur.', '/images/event-3.jpg', 'Forum', 'Sofitel Abidjan Hôtel Ivoire', 'Boulevard Hassan II', 'Abidjan', 'Côte d''Ivoire', '2026-05-10 09:00:00+00', '2026-05-12 17:00:00+00', false, false, 300, 'EUR', 800, 'AfDB Infrastructure', 'https://example.com/register')
ON CONFLICT (slug) DO NOTHING;

-- Seed Jobs
INSERT INTO jobs (slug, title, company_name, company_logo, description, requirements, location, country, contract_type, sector, salary_range, experience_level, application_url, application_email, is_featured, is_urgent, published_at, expires_at) VALUES
('ingenieur-genie-civil-casablanca', 'Ingénieur Génie Civil – Structures', 'COVEC AFRICA', null, 'Vous serez en charge du dimensionnement et du suivi des ouvrages de génie civil dans le cadre de grands projets d''infrastructure. Missions principales : études techniques, suivi de chantier, coordination équipes.', 'Diplôme d''ingénieur en génie civil. Minimum 3 ans d''expérience. Maîtrise AutoCAD et Robot. Français et anglais courants.', 'Casablanca', 'Maroc', 'CDI', 'Génie Civil', '15 000 – 20 000 MAD', '3-5 ans', 'https://example.com/apply', 'recrutement@covec.ma', true, true, '2026-03-10 00:00:00+00', '2026-04-30 00:00:00+00'),
('conducteur-travaux-abidjan', 'Conducteur de Travaux – Bâtiment', 'Bouygues Construction Afrique', null, 'Piloter l''exécution des travaux de bâtiment en assurant le respect des délais, des coûts et des normes qualité/sécurité. Management d''équipes jusqu''à 50 personnes.', 'Diplôme BTS/DUT génie civil ou équivalent. 5 ans d''expérience minimum. Maîtrise MS Project.', 'Abidjan', 'Côte d''Ivoire', 'CDI', 'Management', 'Selon profil', '5-8 ans', null, 'rh@bouygues-africa.com', true, false, '2026-03-08 00:00:00+00', '2026-05-15 00:00:00+00'),
('architecte-urbaniste-dakar', 'Architecte Urbaniste Senior', 'Cabinet BCEOM', null, 'Concevoir et piloter des projets d''urbanisme et d''aménagement urbain durables pour des villes en forte croissance. Participation aux concours internationaux.', 'Diplôme d''architecte DPLG ou équivalent. 7 ans d''expérience en urbanisme. Portfolio requis.', 'Dakar', 'Sénégal', 'CDI', 'Architecture', 'Selon profil', '7+ ans', 'https://example.com/apply', 'careers@bceom.sn', false, false, '2026-03-06 00:00:00+00', '2026-04-20 00:00:00+00'),
('chef-projet-infrastructure-nairobi', 'Chef de Projet Infrastructure Routière', 'VINCI Construction', null, 'Diriger la réalisation d''un projet routier de grande envergure en Afrique de l''Est, en coordination avec les équipes locales et le client.', 'Ingénieur travaux publics. 8 ans d''expérience sur grands projets. Anglais courant obligatoire.', 'Nairobi', 'Kenya', 'CDD', 'Génie Civil', 'Package expatrié', '8+ ans', 'https://vinci.com/careers', null, false, true, '2026-03-04 00:00:00+00', '2026-04-15 00:00:00+00'),
('responsable-hse-thies', 'Responsable HSE – Grands Travaux', 'Eiffage Sénégal', null, 'Mettre en place et animer la politique Hygiène, Sécurité et Environnement sur les chantiers de construction. Formation des équipes.', 'Diplôme HSE ou équivalent. 4 ans d''expérience. Certifications NEBOSH appréciées.', 'Thiès', 'Sénégal', 'CDI', 'HSE', 'Selon profil', '4-6 ans', null, 'hse@eiffage.sn', false, false, '2026-03-02 00:00:00+00', '2026-04-30 00:00:00+00'),
('topographe-rabat', 'Topographe – Grands Projets', 'STRABAG Maroc', null, 'Réaliser les levés topographiques et assurer le suivi géométrique des ouvrages dans le cadre de projets autoroutiers.', 'BTS/Licence en topographie. 2 ans d''expérience. Maîtrise station totale et GPS.', 'Rabat', 'Maroc', 'CDD', 'Topographie', '10 000 – 14 000 MAD', '2-4 ans', 'https://strabag.com/careers', 'jobs@strabag.ma', false, false, '2026-02-28 00:00:00+00', '2026-04-15 00:00:00+00')
ON CONFLICT (slug) DO NOTHING;

-- Seed Companies
INSERT INTO companies (slug, name, logo, description, long_description, category, subcategory, city, country, address, phone, email, website, year_founded, employees_count, services, certifications, projects_completed, is_premium, is_verified, rating, reviews_count) VALUES
('holcim-maroc', 'Holcim Maroc', null, 'Leader mondial des matériaux de construction, solutions ciment et béton pour tous vos projets.', 'Holcim Maroc, filiale du groupe LafargeHolcim, est le leader des matériaux de construction au Maroc. Nous offrons une gamme complète de ciments, bétons et granulats pour tous types de projets, du résidentiel aux grandes infrastructures.', 'Matériaux', 'Cimenterie', 'Casablanca', 'Maroc', '1 Rue des Cimentiers, Ain Sebaa', '+212 522 67 89 00', 'contact@holcim.ma', 'https://www.holcim.ma', 1912, '1000+', '{"Ciment Portland", "Béton prêt à l''emploi", "Granulats", "Solutions éco-responsables"}', '{"ISO 9001", "ISO 14001", "ISO 45001"}', 5000, true, true, 4.9, 156),
('jet-contractors', 'Jet Contractors', null, 'Expert en façades et enveloppes du bâtiment, ingénierie et réalisation de projets complexes.', 'Jet Contractors est le leader marocain et africain dans le domaine des façades et enveloppes du bâtiment. Notre expertise couvre la conception, l''ingénierie et la réalisation de projets architecturaux complexes.', 'Ingénierie', 'Façades', 'Rabat', 'Maroc', '45 Avenue Mohammed V, Agdal', '+212 537 77 88 99', 'info@jetcontractors.ma', 'https://www.jetcontractors.ma', 1991, '500-1000', '{"Façades vitrées", "Murs rideaux", "Bardage métallique", "Ingénierie façades"}', '{"ISO 9001", "Qualibat"}', 800, true, true, 4.8, 89),
('schneider-electric-maroc', 'Schneider Electric Maroc', null, 'Solutions énergétiques et automatisation pour bâtiments intelligents et industrie.', 'Schneider Electric est le leader mondial de la transformation numérique de la gestion de l''énergie et des automatismes. Au Maroc, nous accompagnons les professionnels du bâtiment et de l''industrie dans leur transition énergétique.', 'Équipements', 'Électricité', 'Casablanca', 'Maroc', 'Technopark, Route de Nouaceur', '+212 522 66 77 88', 'morocco@schneider-electric.com', 'https://www.se.com/ma', 1836, '500-1000', '{"Tableaux électriques", "Automatismes", "Gestion énergie", "Domotique"}', '{"ISO 9001", "ISO 14001", "LEED Partner"}', 2000, true, true, 5.0, 234),
('sonasid', 'Sonasid', null, 'Premier sidérurgiste marocain, production d''aciers pour la construction et l''industrie.', 'Sonasid, filiale du groupe ArcelorMittal, est le premier sidérurgiste marocain. Nous produisons une gamme complète d''aciers pour le bâtiment, les infrastructures et l''industrie.', 'Matériaux', 'Acier', 'Casablanca', 'Maroc', 'Zone Industrielle Jorf Lasfar', '+212 523 34 56 78', 'contact@sonasid.ma', 'https://www.sonasid.ma', 1974, '1000+', '{"Rond à béton", "Treillis soudés", "Profilés", "Aciers spéciaux"}', '{"ISO 9001", "NF Acier"}', 10000, false, true, 4.7, 78),
('ciments-afrique', 'Ciments d''Afrique (CIMAF)', null, 'Producteur de ciment présent dans plusieurs pays africains, solutions durables.', 'CIMAF est un acteur majeur de l''industrie cimentière en Afrique, présent dans plus de 10 pays. Notre engagement : fournir des ciments de qualité tout en préservant l''environnement.', 'Matériaux', 'Cimenterie', 'Abidjan', 'Côte d''Ivoire', 'Zone Industrielle de Yopougon', '+225 27 23 45 67 89', 'contact@cimaf.com', 'https://www.cimaf.com', 2008, '500-1000', '{"Ciment Portland", "Ciment composé", "Solutions durables"}', '{"ISO 9001", "ISO 14001"}', 3000, false, true, 4.5, 45),
('eiffage-senegal', 'Eiffage Sénégal', null, 'Groupe de construction et concessions, expert en grands travaux et infrastructures.', 'Eiffage Sénégal est la filiale du groupe Eiffage, l''un des leaders européens du BTP. Nous réalisons des projets majeurs d''infrastructure au Sénégal et en Afrique de l''Ouest.', 'Construction', 'Travaux Publics', 'Dakar', 'Sénégal', '15 Rue Félix Faure, Plateau', '+221 33 821 22 33', 'contact@eiffage.sn', 'https://www.eiffage.sn', 1998, '1000+', '{"Routes", "Ouvrages d''art", "Bâtiments", "Génie civil"}', '{"ISO 9001", "ISO 14001", "ISO 45001"}', 500, false, true, 4.6, 67)
ON CONFLICT (slug) DO NOTHING;
